spring:
  application:
    name: demo_web
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:80/eureka/
    register-with-eureka: true

