spring:
  application:
    name: demo-web
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/static/
    suffix: .html
  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      concurrency: 4

    producer:
      batch-size: 1000

    consumer:
      group-id: myGroup
    template:
      default-topic: topic-1

server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:80/eureka/
    register-with-eureka: true