spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/senseDemo
  application:
    name: demo-service
mybatis:
  mapper-locations: classpath:com/sensetime/demo_service/dao/mapper/*.xml
  type-aliases-package: com.sensetime.entity
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:80/eureka/
    register-with-eureka: true
    fetch-registry: false