spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      concurrency: 4
    producer:
      batch-size: 1000
    consumer:
      group-id: myGroup
    template:
      default-topic: topic-1
  application:
    name: demo-es
server:
  port: 8181
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:80/eureka/